test_data_reader.go
It is very annoying when working with a large file and a directive line
is missing and the first query line fails to parse as a directive.
This change adds the file and line number to the error message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/datadriven/3)
=> show file and line number on directive parse error

datadriven.go, datadriven_test.go, line_parser.go, test_data_reader.go
See individual commits for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/datadriven/2)
=> Misc. datadriven improvements

datadriven_test.go, line_parser.go, test_data_reader.go
My previous PR #2 introduced a bug (wasn't picked up in review).
Also wanted to enhance `ParseLine` as per Radu's suggestion in https://github.com/cockroachdb/datadriven/pull/2#issuecomment-554094575
- `ParseLine` now reports duplicate arguments on a single directive
line. Also added tests to check this.
- there was a missing `err` return, this patch fixes it and adds a
unit test.
- the location prefix would be reported two times, once because
it was embedded in the error object and once because `t.Fatal`
would prepend it again. This patch fixes it.
- the error message upon syntax errors was truncating the input
line. This patch fixes that and also adds column information.
Also checks this behavior via a unit test.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Fix syntax error checks

datadriven.go
Found in https://github.com/cockroachdb/cockroach/pull/42573.
Many tests expect "no output". In these cases we want to avoid
adding a newline character because otherwise `-rewrite`
will change the expected output from a single delimiter:
```
dir
input
----
```
to a double double delimiter:
```
dir
input
----
----
----
----
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/datadriven/5)
=> Avoid adding a newline if the output is empty otherwise

datadriven_test.go, line_parser.go
This is used in CockroachDB in `pkg/sql/opt/memo/memo_test.go` test
`TestStats`, to specify multiple column stat groups side-by-side.
Found via https://github.com/cockroachdb/cockroach/pull/42573.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/datadriven/6)
=> Re-allow duplicate k=v pairs in a directive

datadriven.go, datadriven_test.go
I found this API usage error while attempting to run t.Fatal or t.Skip
inside a test directive: it's not possible to change the status of an
outer test instance while `datadriven.RunTest` has instantiated a
sub-test.
Symptom:
```
test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
```
This patch fixes it by giving the sub-test instance to the
callback. All usages must be updated.
Needed for https://github.com/cockroachdb/cockroach/pull/42250.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/datadriven/7)
=> Ensure the test callback sees the sub-test instance

datadriven.go, datadriven_test.go
:man_facepalming:  I should really have tested this earlier.
Needed for https://github.com/cockroachdb/cockroach/pull/42152
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/datadriven/10)
=> Properly handle Skip in sub-test

datadriven.go, datadriven_test.go, line_parser.go, test_data_reader.go, testdata/subtest
Fixes #8.
This commit removes the one-subtest-per-directive logic and replaces
it by proper subtest support in the input DSL.
A sub-test begins with `subtest <name>` and ends with `subtest end [<name>]`.
- Sub-tests can be nested. However, the name of a nested sub-test must
be prefixed by the name of the enclosing sub-test and a `/`.
- The name is optional after `end`; if present, it must match the
corresponding start directive.
- Obviously "`end`" is not a valid name to start a subtest.
For example:
```
subtest foo
subtest foo/bar
subtest end foo/bar
subtest end
```
This will be used in https://github.com/cockroachdb/cockroach/pull/42250.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Implement subtest sections in input files

datadriven.go
I was running some experiments using a build system that enforces "no
updating sources while the build is running" and the `datadriven`
tests started failing, even when `-rewrite` was not specified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/datadriven/15)
=> Enable running tests if the test inputs are read-only

datadriven.go
Found this while working on #14.
The DSL requires sub-test names to be prefixed by their
enclosing sub-test in the input, to clarify intent.
However the code was passing this string unmodified as first argument
to `t.Run`, which _also_ adds the parent name as prefix. The result
would be a doubly prefixed test name, for example `subtest hai/world`
would cause the sub-test to be named `hai/hai/world`, and
`hello/my/world` would become `hello/hello/my/hello/my/world`.
This patch fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/datadriven/16)
=> Fix the generation of sub-test names

datadriven.go
It's pretty easy to forget to use Walk and instead call RunTest directly
on a directory. This used to silently fail without running any tests. Now
it throws an error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/datadriven/18)
=> Warn when calling RunTest on directory

datadriven-clear/main.go, datadriven.go
When writing many new tests, it is sometimes useful to temporarily clear out all
results from a test file. This commit adds a `datadriven-clear` program that
does that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/datadriven/19)
=> Add program that clears results

datadriven.go, datadriven_test.go, test_data_reader.go, testdata/rewrite/basic-after, testdata/rewrite/basic-before, testdata/rewrite/eof-1-after, testdata/rewrite/eof-1-before, testdata/rewrite/eof-2-after, testdata/rewrite/eof-2-before
This commit adds testing for -rewrite. The `testdata/rewrite` directory contains
pairs of files with before and after output. Note that the "after" output can
itself be regenerated using `-rewrite`.
Fixing two problems related to rewriting testcases that use the double
separator:
- we were adding an extra blank line when the original testfile uses the double
separator;
- we were not adding the expected blank line when the rewritten testfile uses
the double separator.
Note that these two problems were canceling each other out when both the input
and the rewritten testcases use the double separator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/datadriven/22)
=> add rewrite tests and fix some issues

datadriven.go, datadriven_test.go, go.mod, go.sum, testdata/multiline
When there's a lot of output in a datadriven test, it can be challenging
to figure out what went wrong based on the output of the test if the
failure was just a subtle difference.
This commit introduces difflib and produces a unified diff when a test
fails that has more than 5 lines of output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/datadriven/26)
=> feature: print out unified diff for failed tests

datadriven.go
I noticed over in cockroachdb/cockroach that test failures were printed
as originating from `datadriven.go:194` as opposed to the actual test's
invocation of `datadriven.RunTest`. Inserting the missing `t.Helper()`
call seems to have fixed that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/datadriven/28)
=> Add missing t.Helper()

datadriven_test.go, line_parser.go, testdata/directive
This change allows argument values to contain nested parens. For
example "cmd arg=(a, a + (b + c))" produces values "a" and
"a + (b + c)".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/datadriven/31)
=> Allow nested parens in argument values

datadriven.go
In one case, the Fatalf call did not contain the current position and
input.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/datadriven/32)
=> show position in Fatal with long diffs

datadriven.go
int and uint64 were supported, but not int64.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/datadriven/40)
=> support parsing int64

datadriven.go, datadriven_test.go, testdata/walk/ext.test, testdata/walk/noext
Subtests created by `Walk` now exclude extensions of test file names. For
example, if the test `TestFoo` uses `Walk` to test a file `foo.test`, the
subtest name will be `TestFoo/foo` rather than `TestFoo/foo.test`.
This change is motivated by https://github.com/cockroachdb/cockroach/pull/78048#issuecomment-1072739833.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/datadriven/39)
=> ignore test file extensions in Walk

datadriven.go, datadriven_test.go
Support `ScanArgs` invocations that scan multiple arguments for a single key into `[]string`, `[]int`, or `[]uint64`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/datadriven/43)
=> support scanning into a few slice types

datadriven.go, datadriven_test.go
This patch adds scan implementation for float64, time.Duration, and []float64.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/datadriven/45)
=> add scan implementation for float64, time.Duration, and []float64

datadriven.go
This commits add some helpers to assert that we have a certain number of values and for common cases of retrieving one or two values.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/datadriven/47)
=> add helpers for using CmdArg values

datadriven.go
Cosmetic change to standardize on using `td` as the recommended name for the `*TestData` argument. `d` is too generic and can clash with common things (e.g.  the DB in Pebble). Probably half of the CRDB and Pebble code already uses `td`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/datadriven/55)
=> change d argument to td in public APIs
